chore: separate header logic from screens
SlovakNationalGallery/bookmarks.sng.sk pull request #29
Opened 2022-08-25 11:03 UTC by FrantisekMichalSebestyen

This is needed for page transitions to work.

2022-08-29 20:01 UTC, igor-kamil requested changes
see comments. overall 👌

2022-08-30 07:28 UTC, FrantisekMichalSebestyen commented on resources/js/app.js
> +        title: 'Artwork detail'
resolved with prettier :)

2022-08-30 07:29 UTC, FrantisekMichalSebestyen commented on resources/js/app.js
> +      title: 'SNG Codes'
✅

2022-09-02 09:41 UTC, igor-kamil approved these changes
👌 done

2022-09-02 09:43 UTC, merged