Nsng 71 detail UI update
SlovakNationalGallery/bookmarks.sng.sk pull request #38
Opened 2022-10-27 21:15 UTC by igor-kamil

<img width="312" alt="Snímka obrazovky 2022-10-27 o 23 14 27" src="https://user-images.githubusercontent.com/2682941/198399604-b745f723-ddab-434b-aa55-2282005b643e.png">

2022-10-28 07:26 UTC, rastislav-chynoransky requested changes

2022-10-28 07:26 UTC, rastislav-chynoransky commented on resources/js/components/Header.vue
> +                <svg v-if="code" class="h-4 w-auto ml-2" viewBox="0 0 10 18" fill="none" xmlns="http://www.w3.org/2000/svg">
My proposal for dealing with svg's is in my PR:
https://github.com/SlovakNationalGallery/bookmarks.sng.sk/pull/37/files#diff-32a27d5d23c7729f91299c44896683d5c5293286baa0fbce8a9f06850b287c58R8

I'd set dimensions explicitly in pixel units since there are stroked paths and no scaling is desired.
We also don't `viewBox` attribute or `xmlns` (https://stackoverflow.com/questions/18467982/are-svg-parameters-such-as-xmlns-and-version-needed)
```suggestion
                <svg v-if="code" class="h-[18px] w-[10px] ml-2" fill="none">
```

For other svg attributes like `fill`, `stroke`, `stroke-width`, `stroke-linecap`, `stroke-linejoin` I'd prefer to use tailwind classes.

2022-10-28 07:26 UTC, rastislav-chynoransky commented on resources/js/components/Header.vue
> +                :class="[{ 'border-l-black bg-green': isActive }, {'opacity-40' : !count}]"
```suggestion
                :class="{ 'border-l-black bg-green': isActive, 'opacity-40': !count }"
```

2022-10-28 07:26 UTC, rastislav-chynoransky commented on resources/js/components/Header.vue
> +                <div class="font-bold text-base pr-2">{{ count }}</div>
Decrease padding-right

2022-10-28 07:26 UTC, rastislav-chynoransky commented on resources/js/views/Detail.vue
> +        <div class="bg-black rounded-md p-1.5 inline-block -top-8 z-index-0 absolute" v-if="item.code">
```suggestion
        <div class="bg-black rounded-md p-1.5 inline-block -top-8 z-0 absolute" v-if="item.code">
```
But I'm not sure if it's really needed

2022-10-28 07:31 UTC, rastislav-chynoransky commented
Also it seems to me that you don't have the prettier formatter enabled

2022-11-03 08:43 UTC, igor-kamil commented on resources/js/components/ConfirmButton.vue
> +    <button class="border-black rounded-xl border-2 py-4 w-full font-bold active:bg-black active:text-white flex items-center justify-center">
eagle eyes! fixed ✅ 
(regarding refactoring - I see your point. this is good when you see this from outside... let's do it. but not within this task... I created new one for that )

2022-11-03 08:50 UTC, igor-kamil commented on resources/js/components/Header.vue
> +                <svg v-if="code" class="h-4 w-auto ml-2" viewBox="0 0 10 18" fill="none" xmlns="http://www.w3.org/2000/svg">
yes! I really liked your approach with svg-s. Applied.

2022-11-03 09:59 UTC, rastislav-chynoransky reviewed
Please test my suggestions after applying

2022-11-03 09:59 UTC, rastislav-chynoransky commented on resources/js/components/Header.vue
> +                    xmlns="http://www.w3.org/2000/svg">
```suggestion
                <svg v-if="code" class="w-[10px] h-[18px] fill-none ml-2">
```

2022-11-03 09:59 UTC, rastislav-chynoransky commented on resources/js/components/Header.vue
> +                    xmlns="http://www.w3.org/2000/svg">
<svg v-else class="h-[32px] w-[32px] fill-black">

2022-11-03 09:59 UTC, rastislav-chynoransky commented on resources/js/views/Detail.vue
> +                        xmlns="http://www.w3.org/2000/svg">
```suggestion
                    <svg class="mr-3 w-[25px] h-[22px] stroke-black stroke-2 fill-green">
```

2022-11-03 09:59 UTC, rastislav-chynoransky commented on resources/js/views/Detail.vue
> +                    stroke="#32B964" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
```suggestion
                    class="stroke-[#32B964] stroke-2 [stroke-linecap:round] [stroke-linejoin:round]" />
```

2022-11-03 09:59 UTC, rastislav-chynoransky commented on resources/js/views/Detail.vue
> +                    stroke="#32B964" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
```suggestion
                    class="stroke-[#32B964] stroke-2 [stroke-linecap:round] [stroke-linejoin:round]" />
```

2022-11-03 09:59 UTC, rastislav-chynoransky commented on resources/js/views/Detail.vue
> +            class="flex items-center py-2 px-3 mb-4 text-[#32B964] bg-[#E4FAE7] hover:bg-[#caf5d0] active:bg-[#caf5d0] rounded-xl">
We should define these colors in tailwind config

2022-11-03 09:59 UTC, rastislav-chynoransky commented on resources/js/components/Header.vue
> +                    :class="[count ? 'fill-green' : 'fill-white']" xmlns="http://www.w3.org/2000/svg">
```suggestion
                <svg class="stroke-black stroke-2 w-[29px] h-[25px] w-auto" :class="[count ? 'fill-green' : 'fill-white']">
```

2022-11-03 10:01 UTC, rastislav-chynoransky commented
Also please rebase to master and apply new styling to collapsible author component

2022-11-03 10:35 UTC, igor-kamil commented on resources/js/views/Detail.vue
> +            class="flex items-center py-2 px-3 mb-4 text-[#32B964] bg-[#E4FAE7] hover:bg-[#caf5d0] active:bg-[#caf5d0] rounded-xl">
this is going to be replaced with updated design in separated task ( NSNG-75 )

2022-11-03 10:37 UTC, igor-kamil commented on resources/js/components/Header.vue
> +                    xmlns="http://www.w3.org/2000/svg">
here it's another case. I use other SVG not from figma - this one is in better quality. however - it needs to be resized to figma proportions (24px) instead of original (32px)

2022-11-03 10:43 UTC, igor-kamil commented on resources/js/views/Detail.vue
> +                        xmlns="http://www.w3.org/2000/svg">
same here. it's webumenia button to-be-replaced in NSNG-75

2022-11-03 14:18 UTC, rastislav-chynoransky approved these changes
Awesome! 🚀

2022-11-03 14:38 UTC, merged