polymorphic code
SlovakNationalGallery/bookmarks.sng.sk pull request #42
Opened 2022-11-04 18:14 UTC by rastislav-chynoransky

https://jira.sng.sk/browse/NSNG-68

2022-11-07 21:28 UTC, igor-kamil requested changes
the code looks good. 
plase don't forget to update route `/import` https://github.com/SlovakNationalGallery/bookmarks.sng.sk/blob/master/routes/web.php#L30-L33
because that one is actually being used be @ustengrav to run imports -> also it should be able to launch import both for items/codes

2022-11-07 21:28 UTC, igor-kamil commented on database/migrations/2022_11_04_161135_create_items_table.php
> +            $table->string('airtable_id')->unique();
probably it's worth putting an alert ⚠️  in description, that it's necessary to run import from airtable before deploying this. otherwise migrations will fail in deploy (like in my case - because there is no `airtable_id` imported and cannot be `null`)

2022-11-07 21:35 UTC, igor-kamil commented
also we use `php7.4` right now for this project (also this version is configured on server). (actually it should be painless to update config to use php8.1 -> however right now deploy will fail on `composer install`

2022-11-07 21:43 UTC, rastislav-chynoransky commented on database/migrations/2022_11_04_161135_create_items_table.php
> +            $table->string('airtable_id')->unique();
They already are, it's been done in #41

2022-11-07 21:43 UTC, rastislav-chynoransky commented on app/Models/Section.php
> +    }
Will do!

2022-11-07 21:46 UTC, rastislav-chynoransky commented
> also we use `php7.4` right now for this project (also this version is configured on server). (actually it should be painless to update config to use php8.1 -> however right now deploy will fail on `composer install`

Thanks! It should be specified in `composer.json`, currently there is:
```
        "php": "^7.3|^8.0",
```

2022-11-08 09:06 UTC, igor-kamil approved these changes
now it's good. still `/import` is not working anymore. can be done in standalone task

2022-11-08 09:09 UTC, rastislav-chynoransky commented
Ah, sure, i keep forgetting about these routes. Maybe it’s time to write some tests.

2022-11-08 12:15 UTC, igor-kamil commented
nice. and done ✅ 
thanx for the `import` part

2022-11-08 12:16 UTC, igor-kamil approved these changes
🚀

2022-11-08 15:58 UTC, merged