section view
SlovakNationalGallery/bookmarks.sng.sk pull request #43
Opened 2022-11-05 22:28 UTC by rastislav-chynoransky

I'll rebase this branch to master when #42 is merged.
https://jira.sng.sk/browse/NSNG-67

2022-11-08 14:48 UTC, igor-kamil requested changes
in section there should be also back button according the design
<img width="398" alt="Snímka obrazovky 2022-11-08 o 15 46 03" src="https://user-images.githubusercontent.com/2682941/200595614-213c9144-7965-4f06-af77-e11c8873117d.png">
the rest is good!

2022-11-08 14:59 UTC, rastislav-chynoransky commented on resources/js/bootstrap.js
> +})
DRYness :)

2022-11-08 15:02 UTC, rastislav-chynoransky commented
> in section there should be also back button according the design

I forgot to mention this in the comment. I think this puts there more logic since home button leads to home, back button elsewhere. Could we check this with Filip?

2022-11-08 15:17 UTC, igor-kamil commented
You can write him. By my personal preferance - I would prefer back arrow in section - with the meaning "return".

2022-11-09 14:28 UTC, igor-kamil approved these changes
let's just fix conflicts and release it as it is 🚀 
we can solve "`logo` vs `return-arrow`" dispute later (after testing) 😁

2022-11-09 15:25 UTC, merged