Nsng 75 webumenia button
SlovakNationalGallery/bookmarks.sng.sk pull request #44
Opened 2022-11-05 23:08 UTC by igor-kamil

<img width="380" alt="Snímka obrazovky 2022-11-06 o 0 07 36" src="https://user-images.githubusercontent.com/2682941/200145063-d9823211-ef4d-4586-b74b-6b3cfc1d9ba5.png">

detail:

<img width="376" alt="Snímka obrazovky 2022-11-06 o 0 07 21" src="https://user-images.githubusercontent.com/2682941/200145141-c87189db-353b-4992-ad2f-8eee1e7dcbf6.png">

2022-11-05 23:31 UTC, rastislav-chynoransky requested changes

2022-11-05 23:31 UTC, rastislav-chynoransky commented on resources/js/components/WebumeniaButton.vue
> +    <a :href="props.url" target="_blank" class="bg-green p-2.5 rounded-xl block">
```suggestion
    <a :href="props.url" target="_blank" class="bg-green border-2 border-green p-2.5 rounded-xl block">
```

2022-11-06 01:37 UTC, rastislav-chynoransky commented on resources/js/components/AuthoritySummary.vue
> +    <div class="flex items-center">
Good catch! I'd prefer to set `self-center` to the flex item at 6th line to keep the avatar top-aligned.

2022-11-08 12:07 UTC, rastislav-chynoransky approved these changes
Thanks for the changes!
Btw, will the wording of the button change? The capitalized words "Archiv" and "Umenia" seem a bit off...

2022-11-08 12:11 UTC, igor-kamil commented
Yes. The wording will change. It's just temporary. But they can't come up with "proper" idea for weeks... I think this can "accelerate the process" 😅

2022-11-08 12:11 UTC, merged