Nsng 102 update collection view
SlovakNationalGallery/bookmarks.sng.sk pull request #57
Opened 2022-11-17 09:54 UTC by igor-kamil

<img width="331" alt="Snímka obrazovky 2022-11-17 o 10 53 06" src="https://user-images.githubusercontent.com/2682941/202414514-95d5e2c7-b686-4220-8c66-b9f4727bd5d5.png">

<img width="331" alt="Snímka obrazovky 2022-11-17 o 10 53 13" src="https://user-images.githubusercontent.com/2682941/202414532-2d3b05aa-e6e1-403e-8013-327e8c7cc59c.png">

2022-11-17 14:03 UTC, rastislav-chynoransky requested changes
I think this needs more input from Filip.
1) I wouldn't expect the share button to grow with the screen resolution.
2) The title "My collection (4)" should be centered.
3) The share button should do more than just to scroll the element into view – at least to trigger the _real_ share action.

2022-11-19 21:21 UTC, igor-kamil commented on resources/js/views/Collection.vue
> +                    {{ $t('The link does never expire - your collection will stay here even after you close the app.')
from figma. it's supposed to be "final": 
![image](https://user-images.githubusercontent.com/2682941/202871995-c54b4a71-2ce7-4209-8eaa-22f5d6723457.png)

2022-11-19 21:35 UTC, igor-kamil commented
<img width="518" alt="Snímka obrazovky 2022-11-19 o 22 16 59" src="https://user-images.githubusercontent.com/2682941/202872412-ff8b3d08-036a-4566-bc94-b0fd73842679.png">

1. true - fixed ✔️ 
2. yep - fixed ✔️ 
3. I agree. but let's see it as a "half-step" solution. right now it's bit tricky -> just to decide, whether to launch `shareCollection` (with obtaining "sharable url") or `shareUrlDialog` (just sharing already generated "sharable url"). I think the proper solution is some kind of "share modal" - with url and actions. which could be invoked both from header / collection button. what do you think?

2022-11-19 22:03 UTC, rastislav-chynoransky commented on resources/js/views/Collection.vue
> +                    {{ $t('The link does never expire - your collection will stay here even after you close the app.')
Ok, let's just ask about `does never expire`

2022-11-20 00:09 UTC, igor-kamil commented on resources/js/components/Header.vue
> +        <div class="flex-1 px-3 border-l-2 border-transparent text-right" v-if="$route.name === 'my_collection'">
the border has to be defined - to keep the final width equal with the left column. also it needs to be transparent - otherwise it's black ...

2022-11-20 00:10 UTC, igor-kamil commented on resources/js/components/Header.vue
>              <div class="flex px-4 py-2 h-full border-black border-l-2 border-l-transparent transition-colors"
I tested it centred... and I like it more align right - as proposed in the design (this is question for filip...)

2022-11-20 00:16 UTC, igor-kamil commented on resources/js/components/Header.vue
> +    document.getElementById(id).scrollIntoView({
that's how it was made before https://github.com/SlovakNationalGallery/bookmarks.sng.sk/pull/29 🙈  
but I agree... however I see it outside of the scope of this task 😅 
well... this is here just to demonstrate, that we have to do it differently anyway... I see it as a tmp code.

2022-11-20 00:19 UTC, igor-kamil commented on resources/js/components/Survey.vue
> +        <h3 class="text-base font-bold mb-3">
I discussed it with filip and he fixed it:
![image](https://user-images.githubusercontent.com/2682941/202876742-218c7b4e-019e-41de-b57a-465f7243df72.png)

just didn't applied to "handoff"

2022-11-20 00:19 UTC, igor-kamil commented on resources/js/views/Collection.vue
> +                    {{ $t('The link does never expire - your collection will stay here even after you close the app.')
ok. let's discuss this on meeting. I see your point :)

2022-11-20 00:29 UTC, rastislav-chynoransky commented on resources/js/components/Header.vue
> +        <div class="flex-1 px-3 border-l-2 border-transparent text-right" v-if="$route.name === 'my_collection'">
Sorry, yes, I thought it's counted in the flex-item width.

2022-11-20 00:37 UTC, rastislav-chynoransky commented on resources/js/components/Header.vue
> +    document.getElementById(id).scrollIntoView({
Hm, the lesser temp code in production the better, but I see your point.
Could you create a task for that?

2022-11-20 01:17 UTC, igor-kamil commented on resources/js/components/Header.vue
> +    document.getElementById(id).scrollIntoView({
[NSNG-105](https://jira.sng.sk/browse/NSNG-105) ✅

2022-11-20 09:13 UTC, rastislav-chynoransky commented on resources/js/components/Header.vue
> +            <button class="bg-green rounded-xl text-sm px-3 py-1 font-bold ml-auto" @click="scroll('share')">
Last piece 🔝

2022-11-20 21:10 UTC, rastislav-chynoransky approved these changes
🫡

2022-11-20 21:11 UTC, merged